### ISSUE TITLE
Exception in SnippetsCreator

### ISSUE THREAD

**Issue by tehnar** [solariq/sensearch#13]
```
Exception in thread "pool-3-thread-4" java.lang.IndexOutOfBoundsException: toIndex = 1
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1012)
	at java.util.ArrayList.subList(ArrayList.java:1004)
	at com.expleague.sensearch.snippet.SnippetsCreator.getSnippet(SnippetsCreator.java:117)
	at com.expleague.sensearch.snippet.SnippetPhase.accept(SnippetPhase.java:24)
	at com.expleague.sensearch.snippet.SnippetPhase.accept(SnippetPhase.java:11)
	at com.expleague.sensearch.core.SenSeArchImpl.lambda$search$1(SenSeArchImpl.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Как воспроизвести: у меня падало на запросах "село" и "путин", но на другой машине работало нормально.

**Comment by AlvinMax** [comment]
fixed
