### ISSUE TITLE
Index Builder errors

### ISSUE THREAD

**Issue by tehnar** [solariq/sensearch#21]
```
Exception in thread "main" org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /home/tehnar/AU/WikiDocs/IndexTmp/embedding/vecs/LOCK: No such file or directory
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at com.expleague.sensearch.index.plain.EmbeddingImpl.<init>(EmbeddingImpl.java:42)
	at com.expleague.sensearch.index.plain.PlainIndex.<init>(PlainIndex.java:87)
	at com.expleague.sensearch.web.Builder.build(Builder.java:39)
	at com.expleague.sensearch.web.SearchServer.main(SearchServer.java:28)
```

Если создать папку, то ругается на это:

```
Exception in thread "main" java.io.FileNotFoundException: /home/tehnar/AU/SimpleSearch/../WikiDocs/IndexTmp/embedding/rand (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.expleague.sensearch.index.plain.EmbeddingImpl.<init>(EmbeddingImpl.java:56)
	at com.expleague.sensearch.index.plain.PlainIndex.<init>(PlainIndex.java:87)
	at com.expleague.sensearch.web.Builder.build(Builder.java:39)
	at com.expleague.sensearch.web.SearchServer.main(SearchServer.java:28)
```

Если создать пустой файл с таким путем, то 

```
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lcom.expleague.commons.math.vectors.Vec;
	at com.expleague.sensearch.index.plain.EmbeddingImpl.<init>(EmbeddingImpl.java:71)
	at com.expleague.sensearch.index.plain.PlainIndex.<init>(PlainIndex.java:87)
	at com.expleague.sensearch.web.Builder.build(Builder.java:39)
	at com.expleague.sensearch.web.SearchServer.main(SearchServer.java:28)
```

**Comment by tehnar** [comment]
Третья ошибка мб потому, что файлик `embedding/rand` пустой
