### ISSUE TITLE
Cannot run SearchServer

### ISSUE THREAD

**Issue by tehnar** [solariq/sensearch#29]
```
Exception in thread "main" org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /home/tehnar/AU/WikiDocs/IndexTmp/embedding/vecs/LOCK: No such file or directory
	at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
	at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
	at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
	at com.expleague.sensearch.index.plain.EmbeddingImpl.<init>(EmbeddingImpl.java:41)
	at com.expleague.sensearch.index.plain.PlainIndex.<init>(PlainIndex.java:87)
	at com.expleague.sensearch.web.Builder.build(Builder.java:39)
	at com.expleague.sensearch.web.SearchServer.main(SearchServer.java:28)
```

All values in config.json are default (from repo)

**Comment by tehnar** [comment]
Ок, нужно было сбилдить индекс. Если его билдить, то бросается 
```
Exception in thread "main" java.io.IOException: java.lang.IllegalArgumentException: Vector dimensions differs. Left: 130, while right: 50
	at com.expleague.sensearch.donkey.plain.PlainIndexBuilder.buildIndex(PlainIndexBuilder.java:276)
	at com.expleague.sensearch.web.Builder.build(Builder.java:40)
	at com.expleague.sensearch.web.SearchServer.main(SearchServer.java:28)
Caused by: java.lang.IllegalArgumentException: Vector dimensions differs. Left: 130, while right: 50
	at com.expleague.commons.math.vectors.VecTools.checkBasisesEquals(VecTools.java:216)
	at com.expleague.commons.math.vectors.VecTools.multiply(VecTools.java:148)
	at com.expleague.sensearch.donkey.plain.EmbeddingBuilder.lambda$new$0(EmbeddingBuilder.java:88)
	at com.expleague.sensearch.donkey.plain.EmbeddingBuilder.addToTables(EmbeddingBuilder.java:106)
	at com.expleague.sensearch.donkey.plain.EmbeddingBuilder.add(EmbeddingBuilder.java:123)
	at com.expleague.sensearch.donkey.plain.EmbeddingBuilder.lambda$addAll$1(EmbeddingBuilder.java:131)
	at gnu.trove.map.hash.TLongObjectHashMap.forEachEntry(TLongObjectHashMap.java:417)
	at com.expleague.sensearch.donkey.plain.EmbeddingBuilder.addAll(EmbeddingBuilder.java:130)
	at com.expleague.sensearch.donkey.plain.PlainIndexBuilder.buildIndex(PlainIndexBuilder.java:255)
	... 2 more
```

**Comment by tehnar** [comment]
Индекс строится, но сервак не запускается
Кажется, проблема была в `PlainIndex` вот здесь:
```
private static final Options DEFAULT_DB_OPTIONS = new Options()
      .cacheSize(DEFAULT_CACHE_SIZE)
      .createIfMissing(false)
      .errorIfExists(true)
      .compressionType(CompressionType.SNAPPY);
```

Похоже, что `errorIfExists` не нужен, я его убрал из кода, если я все сделал правильно, то просто закройте issue

**Comment by SandMV** [comment]
Да, видимо, я не исправил опции, когда скопировал их из билдера. errorIfExists должен быть false, конечно
